openapi: 3.0.0
info:
  version: 1.0.0
  title: my-tracker
servers:
  - url: http://localhost:8080/api
paths:
  /account/:
    get:
      summary: Get account details
      operationId: listUser
      tags:
        - account
      responses:
        '200':
          description: Account of your user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account nof found in db
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add new account
      description: ''
      operationId: addPet
      requestBody:
        description: Add new account after registration
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account of your user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        default:
          description: Default error sample response
      tags:
        - account
  /organization/:
    summary: all about org. Add, delete, edit
    get:
      summary: Get all my organiztion
      description: ''
      operationId: getOrgs
      responses:
        '200':
          description: Your organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        default:
          description: Default error sample response
      tags:
        - organization
    post:
      summary: Add organiztion
      description: ''
      operationId: addOrg
      requestBody:
        description: Organization in JSON
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: Account of your user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Common error
        default:
          description: Default error sample response
      tags:
        - organization
  /organization/{organizationId}:
    delete:
      summary: Delete organiztion
      operationId: deleteOrg
      parameters:
        - in: path
          name: organizationId
          required: true
          schema:
            type: 'integer'
      responses:
        '200':
          description: Success
        '403':
          description: Access denied for this user
        '404':
          description: Organization not found
        '400':
          description: Common error
        default:
          description: Default error sample response
      tags:
        - organization
    put:
      summary: Update organiztion
      operationId: updateOrg
      parameters:
        - in: path
          name: organizationId
          required: true
          schema:
            type: 'integer'
      requestBody:
        description: Organization JSON
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: Success
        '403':
          description: Access denied for this user
        '404':
          description: Organization not found
        '400':
          description: Common error
        default:
          description: Default error sample response
      tags:
        - organization
  /project/:
    summary: all about project. Add, delete, edit
    get:
      summary: Get all organization by project
      description: ''
      operationId: getProjects
      parameters:
        - in: query
          name: organizationId
          description: Org id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Projects in org
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        default:
          description: Default error sample response
      tags:
        - project
    post:
      summary: Add project
      description: ''
      operationId: addProj
      parameters:
        - in: query
          name: organizationId
          description: Org id for new project
          required: true
          schema:
            type: integer
      requestBody:
        description: Project
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Account of your user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '403':
          description: Access denied for organization
        '404':
          description: Organization not found
        '400':
          description: Common error
        default:
          description: Default error sample response
      tags:
        - project


components:
  schemas:
    Account:
      type: object
      required:
        - login
        - passwordHash
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        passwordHash:
          type: string
    Organization:
      type: object
      required:
        - organizationName
      properties:
        id:
          type: integer
          format: int64
        organizationName:
          type: string
        owner:
          $ref: '#/components/schemas/Account'
    Project:
      type: object
      required:
        - projectName
      properties:
        id:
          type: integer
          format: int64
        projectName:
          type: string
        organization:
          $ref: '#/components/schemas/Organization'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
